#!/usr/local/bin/python3

import argparse
import simpleseq
import multiprocessing
import os


def parse_args():
    p = argparse.ArgumentParser(description='merge annotations from drop-seq and in-drop')
    p.add_argument('platform', choices=['in_drop', 'drop_seq', 'mars1_seq', 'mars2_seq'],
                   help='which platform are you merging annotations from?')
    p.add_argument('-b', '--basespace-sample', metavar='B',
                   help='name of s3 folder containing fastq files to be downloaded')
    p.add_argument('-t', '--access-token', metavar='T', help='basespace access token')
    p.add_argument('-i', '--index', metavar='I', help='genome index folder')
    p.add_argument('-o', '--output-directory', metavar='O',
                   help='name of output directory')
    return p.parse_args()


if __name__ == '__main__':
    args = parse_args()
    simpleseq.io.BaseSpace.download_sample(
            sample_id=args.basespace_sample, dest_path=args.output_directory,
            access_token=args.access_token)

    barcode = []
    genomic = []
    for file_ in os.listdir(args.output_directory):
        if 'r1' in file_.lower():
            barcode.append(file_)
        if 'r2' in file_.lower():
            genomic.append(file_)

    merge_function = getattr(simpleseq.sequence.merge_functions, args.platform)
    if not args.output_directory.endswith('/'):
        args.output_directory += '/'
    output_file = args.output_directory + 'merged.fastq'
    merged = simpleseq.sequence.fastq.merge_fastq(
        merge_function=merge_function, fout=output_file, genomic=genomic,
        barcode=barcode)
    n_threads = multiprocessing.cpu_count() - 1
    simpleseq.sam.STAR.align(fastq_file=merged, index=args.index, n_threads=n_threads,
                             temp_dir=args.output_directory)
