#!/usr/local/bin/python3

import argparse
import simpleseq
import pickle

def parse_args():
    p = argparse.ArgumentParser(description='merge annotations from drop-seq and in-drop')
    p.add_argument('-s', '--samfile', metavar='S',
                   help='sam file containing reads/molecules to be counted')
    p.add_argument('-g', '--gtf', metavar='G', help='GTF Annotation file')
    p.add_argument('-a', '--alignment-summary', metavar='A',
                   help='Alignment Summary from STAR Alignment')
    p.add_argument('-o', '--output', metavar='O', help='name of output pickled object')
    return p.parse_args()

if __name__ == '__main__':
    args = parse_args()
    rd = simpleseq.sam.SamReader(args.samfile)
    coo, genes, cells = rd.molecule_counts(args.samfile, args.gtf, args.alignment_summary)
    with open(args.output, 'wb') as f:
        pickle.dump({'coo': coo, 'genes': genes, 'cells': cells}, f)
