#!/usr/local/bin/python3

import sys
from subprocess import call


def main(output_prefix, number_records, genomic, barcode):
    if genomic.endswith('.gz'):
        raise ValueError('cannot extract from zipped files, please unzip first')
    args = 'head -n {number_records} {file} > {prefix}_{record_type}.fastq'
    number_records = str(int(number_records) * 4)
    call(args.format(number_records=number_records, file=genomic, prefix=output_prefix, record_type='genomic'),
         shell=True)
    if barcode:
        if barcode.endswith('.gz'):
            raise ValueError('cannot extract from zipped files, please unzip first')
        call(args.format(number_records=number_records, file=barcode, prefix=output_prefix, record_type='barcode'),
             shell=True)


if __name__ == "__main__":
    if len(sys.argv) == 4:
        _, output_prefix, number_records, genomic = sys.argv
        barcode = None
    elif len(sys.argv) == 5:
        _, output_prefix, number_records, genomic, barcode = sys.argv
    else:
        print('usage: extract_test_fastq output_prefix number_records genomic barcode[optional]')
        sys.exit(2)
    main(output_prefix, number_records, genomic, barcode)