#!/usr/local/bin/python3

import matplotlib
matplotlib.use('Agg')

from sys import argv
import simpleseq


def main(samfile, num_reads=int(5e5)):
    simpleseq.sam.get_RMT_histogram(samfile, num_reads)


if __name__ == "__main__":
    main(*argv[1:])